try to retrieve qgis logs

diff --git a/.github/workflows/ogc.yml b/.github/workflows/ogc.yml
--- a/.github/workflows/ogc.yml
+++ b/.github/workflows/ogc.yml
@@ -88,10 +88,20 @@ jobs:
       - name: Run WMS 1.3.0 OGC tests
         run: |
           source venv/bin/activate && ./pyogctest/pyogctest.py -s wms130 -e
-          docker compose -f .ci/ogc/docker-compose.yml up -d
-          source venv/bin/activate && ./pyogctest/pyogctest.py -n ogc_qgis -s wms130 -v -u http://$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' qgis_server_nginx)/qgisserver_wms130
+          docker compose -f .ci/ogc/docker-compose.yml up > docker-compose.log 2>&1 &
+          source venv/bin/activate && ./pyogctest/pyogctest.py -n ogc_qgis -s wms130 -v -u http://$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' qgis_server_nginx)/qgisserver_wms130 || echo "FAILED"
         env:
           DOCKER_IMAGE: ${{ steps.docker-build.outputs.imageid }}
+
+      - name: Push artifact
+        id: push_artifact
+        run: tar -cvzf docker-compose.tgz docker-compose.log
+
+      - uses: actions/upload-artifact@v4
+        with:
+          name: docker-compose.tgz
+          path: ./docker-compose.tgz
+          retention-days: 1
 
       - name: Run OGC API Features 1.0 tests
         run: |
